USE [master]
GO

/****** Object:  Database [Artsys]    Script Date: 5/5/2024 13:02:57 ******/
CREATE DATABASE [Artsys]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Artsys', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Artsys.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Artsys_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Artsys_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Artsys].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Artsys] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Artsys] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Artsys] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Artsys] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Artsys] SET ARITHABORT OFF 
GO

ALTER DATABASE [Artsys] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Artsys] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Artsys] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Artsys] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Artsys] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Artsys] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Artsys] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Artsys] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Artsys] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Artsys] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Artsys] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Artsys] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Artsys] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Artsys] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Artsys] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Artsys] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Artsys] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Artsys] SET RECOVERY FULL 
GO

ALTER DATABASE [Artsys] SET  MULTI_USER 
GO

ALTER DATABASE [Artsys] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Artsys] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Artsys] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Artsys] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Artsys] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Artsys] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Artsys] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Artsys] SET  READ_WRITE 
GO

